theme: jekyll-theme-time-machine
title: Patrick's Personal Page
show_downloads: false
<link rel="icon"  type="image/png"    href="https://www.nasa.gov/centers/goddard/images/content/638831main_globe_east_2048.jpg">
